apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos

metadata:
  name: order-http-error-demo
  namespace: default

spec:
  mode: one

  selector:
    namespaces:
      - default
    labelSelectors:
      app: order-service

  target: Request
  port: 8082
  method: POST
  path: /orders

  abort: true

  duration: "30s"