services:

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productdb
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  product-service:
    image: product-service:1.0
    container_name: product-service
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres-data: