apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: inventory-network-loss-test
  namespace: default
spec:
  action: loss
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: inventory-service
  loss:
    loss: "70"
    correlation: "0"
  direction: to
  duration: "60s"