apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: inventory-network-loss
  namespace: default
spec:
  action: loss
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: inventory-service
  loss:
    loss: "50"
    correlation: "0"
  direction: to
  duration: "30s"