apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-loss-client
  namespace: default
spec:
  action: loss
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      chaos-test: loss-client
  loss:
    loss: "70"
    correlation: "0"
  direction: to
  duration: "60s"