spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/productdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: product-service
management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true