spring.application.name=recovery-engine

server.port=8090

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
recovery.threshold.latency-seconds=1.0
recovery.threshold.cpu-percent=80.0
recovery.threshold.error-rate=0.10
recovery.minimum-unhealthy-signals=1
prometheus.url=http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
recovery.threshold.memory-percent=50.0
recovery.consecutive-unhealthy-evaluations=3